import {ButtonLink} from '@/components/site/ButtonLink'
import Link from 'next/link'

type GuideSection = {title: string; text: string}

export function PlanningGuide({eyebrow, title, intro, sections, callout}: {eyebrow: string; title: string; intro: string; sections: GuideSection[]; callout: {title: string; text: string}}) {
  return <div className="space-y-16 md:space-y-20">
    <section className="overflow-hidden rounded-[2rem] border border-[#d5d7cb] bg-[#eef1e8] px-6 py-12 md:px-12 md:py-16"><div className="max-w-4xl"><div className="text-xs font-bold uppercase tracking-[0.2em] text-[color:var(--accent)]">{eyebrow}</div><h1 className="mt-5 font-serif text-5xl leading-[0.98] tracking-[-0.045em] text-[color:var(--fg)] md:text-7xl">{title}</h1><p className="mt-7 max-w-3xl text-lg leading-8 text-[color:var(--muted)] md:text-xl">{intro}</p><div className="mt-9 flex flex-wrap gap-3"><ButtonLink href="/create-a-will" label="Start a will outline" /><ButtonLink href="/find-an-attorney" label="Find an attorney" style="secondary" /></div></div></section>
    <section className="grid gap-5 md:grid-cols-2">{sections.map((section, index) => <article key={section.title} className="rounded-2xl border border-[color:var(--border)] bg-white p-7 shadow-[0_12px_32px_rgba(29,46,41,0.05)]"><div className="text-xs font-bold tracking-[0.18em] text-[color:var(--accent)]">{String(index + 1).padStart(2, '0')}</div><h2 className="mt-4 font-serif text-3xl tracking-[-0.03em] text-[color:var(--fg)]">{section.title}</h2><p className="mt-4 leading-7 text-[color:var(--muted)]">{section.text}</p></article>)}</section>
    <aside className="rounded-2xl border-l-4 border-[#a58348] bg-[#f9f6ed] px-6 py-7 md:px-8"><h2 className="font-serif text-3xl text-[color:var(--fg)]">{callout.title}</h2><p className="mt-4 max-w-4xl leading-7 text-[color:var(--muted)]">{callout.text}</p></aside>
    <section className="grid gap-8 border-t border-[color:var(--border)] pt-12 lg:grid-cols-[0.8fr_1.2fr]"><div><div className="text-xs font-bold uppercase tracking-[0.2em] text-[color:var(--accent)]">Keep learning</div><h2 className="mt-4 font-serif text-4xl tracking-[-0.035em] text-[color:var(--fg)]">Build a plan that fits together.</h2></div><div className="grid gap-4 sm:grid-cols-2"><Link href="/wills" className="rounded-xl border border-[color:var(--border)] p-5 font-semibold text-[color:var(--fg)] hover:border-[#789b80]">Understanding wills <span className="mt-2 block text-sm font-normal text-[color:var(--muted)]">Directions for property, executors, and guardians.</span></Link><Link href="/trusts" className="rounded-xl border border-[color:var(--border)] p-5 font-semibold text-[color:var(--fg)] hover:border-[#789b80]">Understanding trusts <span className="mt-2 block text-sm font-normal text-[color:var(--muted)]">Property management and distribution terms.</span></Link></div></section>
    <p className="border-t border-[color:var(--border)] pt-6 text-sm leading-6 text-[color:var(--muted)]">This guide is general education only. State law, document language, asset ownership, beneficiary designations, tax rules, and family circumstances can substantially change the result. Seek advice from a qualified attorney and tax professional before acting.</p>
  </div>
}
